import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className="bg-gray-100 text-gray-900"
      >
        <header className="p-4 bg-blue-600 text-white font-bold">
          Catálogo de Produtos
        </header>
        <main className="p-6">
          {children}
        </main>
        <footer p-4 text-center text-sm text-gray-500>
          © 2025 - Meu Catálogo
        </footer>
      </body>
    </html>
  );
}
